### Listado productos - Funciona
###
GET http://localhost:8082/api/catalogo

###
GET http://localhost:8082/api/login

###
GET http://localhost:8082/api/signup

###
GET http://localhost:8082/api/catalogo
